#!/usr/bin/ash

run_hook () {
  if [ -n "${ip}" ]; then
    IFS=":"
    set -- ${ip}
    address="$1" gateway="$3" subnet="$4" interface="$6" method="$7"
    if [ -z "${interface}" ]; then
      interface="eth0"
    fi
    unset IFS

    IFS="."
    set -- ${interface}
    parent="$1" vlan="$2"
    if [ -n "${vlan}" ]; then
      if ip link add link "${parent}" name "${interface}" type vlan id "${vlan}"; then
        ip link set dev "${parent}" up
      else
        printf "%s\n" "Failed to add VLAN device"
      fi
    fi
    unset IFS

    if [ -h "/sys/class/net/${interface}" ]; then
      if [ "${method}" = "dhcp" ]; then
        if dhclient -1 -lf /run/dhclient.leases "${interface}"; then
          killall dhclient
        else
          printf "%s\n" "Failed to request address via DHCP"
        fi
      else
          ip link set dev "${interface}" up
          ip addr add "${address}/${subnet}" dev "${interface}"
          printf "%s: %s\n" "Address" "${address}" "Subnet" "${subnet}"
          ip route add default via "${gateway}" dev "${interface}"
          printf "%s: %s\n" "Gateway" "${gateway}"
          printf "\n"
      fi
    else
      printf "%s\n" "Network device unavailable"
    fi
  else
    printf "%s\n" "Network configuration unavailable"
  fi

  if [ -n "${cryptdevice}" ]; then
    mkdir -p /dev/pts/
    mount -t devpts devpts /dev/pts/
    touch /var/log/lastlog
    touch /run/utmp

    printf "%s=%s\n" "cryptdevice" "${cryptdevice}" > /run/cryptdevice
    if dropbear -E -s -j -k $(printf -- " -r %s" $(ls /etc/dropbear/*_host_key)) -c unlock 2> /dev/null; then
      printf "%s\n" "SSH server is running..."
    else
      printf "%s\n" "Failed to start SSH server"
    fi
    printf "\n"

    unlock

    killall dropbear

    if [ -n "${vlan}" ]; then
      if ! ip link delete "${interface}"; then
        printf "%s\n" "Failed to delete VLAN device"
      fi
    fi
  else
    printf "%s\n" "Device configuration unavailable"
  fi
}
